# Step 1: Installation and Setup

In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.2.0

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Step 2: Data Preprocessing

In [ ]:
# reading the file
dataset = pd.read_csv('Churn_Modelling.csv')

In [ ]:
dataset.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [ ]:
# Selecting the Independent and Dependent variables
x = dataset.drop(labels=['RowNumber','CustomerId','Surname','Exited'], axis=1)
y = dataset['Exited']

In [ ]:
x.head(10)

   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10
5          645     Spain    Male  ...          1               0        149756.71
6          822    France    Male  ...          1               1         10062.80
7          376   Germany  Female  ...          1               0        119346.88
8          501    France    Male  ...          0               1         74940.50
9          684    France    Male  ...          1               1         71725.73

[10 rows x 10 columns]

In [ ]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [ ]:
# Encoding the categorical data
from sklearn.preprocessing import LabelEncoder

In [ ]:
label_1 = LabelEncoder()
x['Geography'] = label_1.fit_transform(x['Geography'])

In [ ]:
x.head()

   CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0  Female  ...          1               1        101348.88
1          608          2  Female  ...          0               1        112542.58
2          502          0  Female  ...          1               0        113931.57
3          699          0  Female  ...          0               0         93826.63
4          850          2  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [ ]:
label_2 = LabelEncoder()
x['Gender'] = label_2.fit_transform(x['Gender'])

In [ ]:
x.head(8)

   CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0       0  ...          1               1        101348.88
1          608          2       0  ...          0               1        112542.58
2          502          0       0  ...          1               0        113931.57
3          699          0       0  ...          0               0         93826.63
4          850          2       0  ...          1               1         79084.10
5          645          2       1  ...          1               0        149756.71
6          822          0       1  ...          1               1         10062.80
7          376          1       0  ...          1               0        119346.88

[8 rows x 10 columns]

In [ ]:
# Avoiding the Dummy variable trap
x = pd.get_dummies(x, drop_first=True, columns=['Geography'])

In [ ]:
x.head(8)

   CreditScore  Gender  Age  ...  EstimatedSalary  Geography_1  Geography_2
0          619       0   42  ...        101348.88            0            0
1          608       0   41  ...        112542.58            0            1
2          502       0   42  ...        113931.57            0            0
3          699       0   39  ...         93826.63            0            0
4          850       0   43  ...         79084.10            0            1
5          645       1   44  ...        149756.71            0            1
6          822       1   50  ...         10062.80            0            0
7          376       0   29  ...        119346.88            1            0

[8 rows x 11 columns]

In [ ]:
# Splitting the dataset into train and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [ ]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
x_train

array([[ 0.16958176, -1.09168714, -0.46460796, ...,  1.10643166,
        -0.5698444 ,  1.74309049],
       [-2.30455945,  0.91601335,  0.30102557, ..., -0.74866447,
         1.75486502, -0.57369368],
       [-1.19119591, -1.09168714, -0.94312892, ...,  1.48533467,
        -0.5698444 , -0.57369368],
       ...,
       [ 0.9015152 ,  0.91601335, -0.36890377, ...,  1.41231994,
        -0.5698444 , -0.57369368],
       [-0.62420521, -1.09168714, -0.08179119, ...,  0.84432121,
        -0.5698444 ,  1.74309049],
       [-0.28401079, -1.09168714,  0.87525072, ...,  0.32472465,
         1.75486502, -0.57369368]])

In [ ]:
x_test

array([[-0.55204276, -1.09168714, -0.36890377, ...,  1.61085707,
         1.75486502, -0.57369368],
       [-1.31490297, -1.09168714,  0.10961719, ...,  0.49587037,
        -0.5698444 , -0.57369368],
       [ 0.57162971, -1.09168714,  0.30102557, ..., -0.42478674,
        -0.5698444 ,  1.74309049],
       ...,
       [-0.74791227,  0.91601335, -0.27319958, ...,  0.71888467,
        -0.5698444 ,  1.74309049],
       [-0.00566991,  0.91601335, -0.46460796, ..., -1.54507805,
         1.75486502, -0.57369368],
       [-0.79945688,  0.91601335, -0.84742473, ...,  1.61255917,
         1.75486502, -0.57369368]])

# Step 3: Building the Model

In [ ]:
# Creating an object (Initilizing the ANN)
model = tf.keras.models.Sequential()

In [ ]:
# Adding input layer and first hidden layer
# 1) units = 6
# 2) activation function = ReLU
# 3) input dimention = 11
model.add(tf.keras.layers.Dense(units=6, activation='relu', input_dim = 11))

In [ ]:
# Adding second hidden layer
model.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [ ]:
# Output layer
model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [ ]:
# Compiling the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 6)                 72
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 42
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 7
=================================================================
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________

# Step 4: Training the model

In [ ]:
model.fit(x_train, y_train.to_numpy(), batch_size=10, epochs=20)

Epoch 1/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4920 - accuracy: 0.7979
Epoch 2/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4415 - accuracy: 0.8056
Epoch 3/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4308 - accuracy: 0.8108
Epoch 4/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4238 - accuracy: 0.8194
Epoch 5/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4184 - accuracy: 0.8229
Epoch 6/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4136 - accuracy: 0.8267
Epoch 7/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4090 - accuracy: 0.8286
Epoch 8/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4062 - accuracy: 0.8296
Epoch 9/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4039 - accuracy: 0.8307
Epoch 10/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4022 - accuracy: 0.8303
Epoch 11/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4011 - accuracy: 0.8331
Epoch 12/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4001 - accuracy: 0.8342
Epoch 13/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3986 - accuracy: 0.8347
Epoch 14/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3974 - accuracy: 0.8355
Epoch 15/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3962 - accuracy: 0.8357
Epoch 16/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3939 - accuracy: 0.8359
Epoch 17/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3920 - accuracy: 0.8365
Epoch 18/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3886 - accuracy: 0.8385
Epoch 19/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3834 - accuracy: 0.8410
Epoch 20/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3778 - accuracy: 0.8443

# Step 5: Model evaluation and prediction

In [ ]:
# Evaluate the model
test_loss, test_acc = model.evaluate(x_test, y_test.to_numpy())

63/63 [==============================] - 0s 1ms/step - loss: 0.3730 - accuracy: 0.8460

In [ ]:
print('Test Accuracy: {}'.format(test_acc))

Test Accuracy: 0.8460000157356262

In [ ]:
y_pred = model.predict_classes(x_test)

WARNING:tensorflow:From <ipython-input-33-bae1a118294d>:1: Sequential.predict_classes (from tensorflow.python.keras.engine.sequential) is deprecated and will be removed after 2021-01-01.
Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).

In [ ]:
print(y_pred)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]

In [ ]:
print(y_test)

9394    0
898     1
2398    0
5906    0
2343    0
       ..
1037    0
2899    0
9549    0
2740    0
6690    0
Name: Exited, Length: 2000, dtype: int64

In [ ]:
y_test = y_test.to_numpy()

In [ ]:
print(y_pred[11]), print(y_test[11])

[0]
0

(None, None)

In [ ]:
# confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1523   72]
 [ 236  169]]

In [ ]:
acc_cm = accuracy_score(y_test, y_pred)
print(acc_cm)

0.846